CREATE TABLE VEICULO (
    ID_VEICULO SERIAL PRIMARY KEY NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    ANO_FABRICACAO INTEGER NOT NULL,
    PLACA VARCHAR(7) NOT NULL
);

CREATE TABLE ACESSORIO (
    ID_ACESSORIO SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL
);